### ISSUE TITLE
drone_msgs config error

### ISSUE THREAD

**Issue by youngjae41** [w407022008/DroneSys#1]
Hello

Thanks for sharing good code

I'm testing this source but getting an error

![image](https://user-images.githubusercontent.com/55374072/201251292-37905bd0-a7a9-44ce-bf43-f50b1fd40c98.png)

**Comment by w407022008** [comment]
hi, i think you didn't make msgs firstly. 
pls make it
`catkin_make --source Modules/msgs --build build/msgs`
