### ISSUE TITLE
How to use rpg_mpc

### ISSUE THREAD

**Issue by lgh5054** [w407022008/DroneSys#2]
Hello, thank you for the amazing update.

How to use rpg_mpc control with PX4 Frimware?
I plan to use it with histo planner.

**Comment by w407022008** [comment]
Hello, thanks for your interest. No updates have been completed as of yet, I'm currently shifting the center of my work to the hardware and your request will be attended to in the future.

**Comment by w407022008** [comment]
fixed. you could have try with [Firmware_PX4_v1.15.2](https://github.com/w407022008/Firmware_PX4_v1.15.2).
